### ISSUE TITLE
✔Start a project to manage labels

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/issues-repo#10]
### I have done the items below . . .

- [X] I have created a title but left the ✔️ emoji behind.

### Description

Create a repo and associated issues to for a new label manager tool.
This means create a repo, name, and some basic info and issues about the basics of what the tool should do.

### Acceptance Criteria

**This issue is finished when:**
- [ ] Figure out a name for the tool
- [ ] Repo created
- [ ] Basic empty project created
- [ ] Issues on the features to implement created

### ToDo Items

- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [X] Issue linked to the proper project

**Comment by CalvinWilkinson** [comment]
Closed

Reason:
It was discovered that the github organization can set default labels for new repositories.  This means that a manager is not required anymore once the defaults are setup.
