### ISSUE TITLE
🚧Create template repo for C# library projects

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/issues-repo#38]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_\<title\>_**' section.

### Description

Create a template repo for C# library projects.

### Acceptance Criteria

**This issue is finished when:**
- [x] Template repo created

### ToDo Items

- [X] Priority label added to issue.  Refer to _**Change Type Labels**_ section below.

### Related Work

- #28 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
