### ISSUE TITLE
Create issue for each project to setup CLA Assistant

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/issues-repo#39]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_\<title\>_**' section.

### Description

Go to each major project and create an issue to setup [CLA Assistant](https://github.com/cla-assistant/cla-assistant) for the project.

This will help manage the signing of the license agreements using PRs for all contributors.

### Acceptance Criteria

**This issue is finished when:**
- [x] ~Issue created for each major project~

### ToDo Items

- [x] Priority label added to issue.  Refer to _**Change Type Labels**_ section below.
- [x] Issue linked to the proper project
- [x] Issue linked to proper milestone

### Additional information below:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                                                                                |
|---------------------|--------------------------------------------------------------------------------------|
| Bug Fixes           | https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%90%9Bbug                     |
| Breaking Changes    | https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%92%A3breaking%20changes      |
| Enhancement         | https://github.com/KinsonDigital/Velaptor/labels/enhancement                         |
| Workflow Changes    | https://github.com/KinsonDigital/Velaptor/labels/workflow                            |
| Code Doc Changes    | https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%93%91documentation%2Fcode    |
| Product Doc Changes | https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%93%9Ddocumentation%2Fproduct |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kselena** [comment]
@CalvinWilkinson  Can I work on this one?

**Comment by CalvinWilkinson** [comment]
Yes you can.  I assigned it to you.

**Comment by kselena** [comment]
Issue closed. 

Reason: 
Created issue below to set up CLA Assistant for only one project.  The issue creations for the other projects will come from KinsonDigital/Velaptor.
- KinsonDigital/Velaptor#348
