### ISSUE TITLE
🚧Create issue for each project to fix broken label link

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/issues-repo#40]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_\<title\>_**' section.

### Description

Create an issue for each currently existing project plus the template repositories to fix the broken link for the new feature label.

The label was changed but the link is still pointing to the old enhancement label.  The old enhancement label was changed and this is how the link has become broken.

NOTE: Not all projects even have a project item issue template.  Check first to see if it does and if so, create an issue to fix it.  If not, do not create an issue.

### Acceptance Criteria

**This issue is finished when:**
- [x] Issue created for project Velaptor
- [x] Issue created for project CASL
- [x] Issue created for project BranchValidator
- [x] Issue created for project GitHubData
- [x] Issue created for project Infrastructure
- [x] Issue created for project VersionMiner
- [x] Issue created for project VersionValidator
- [x] Issue created for project GotNuget
- [x] Issue created for project issues-repo
- [x] Issue created for project IssueScanner
- [x] Issue created for project TagVerifier
- [x] Issue created for project ReleaseAnnouncer
- [x] Issue created for project CSharpLibTemplateRepo
- [x] Issue created for project DotNetGitHubActionTemplate
- [x] Issue created for project SWCM
- [x] Issue created for project KDActionUtils
- [x] Issue created for project GitHubReleaseChecker

### ToDo Items

- [ ] Draft pull request created and linked to this issue
- [x] Priority label added to issue.  Refer to _**Change Type Labels**_ section below.
- [x] Issue linked to the proper project

### Additional information below:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                                                                                |
|---------------------|--------------------------------------------------------------------------------------|
| Bug Fixes           | https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%90%9Bbug                     |
| Breaking Changes    | https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%92%A3breaking%20changes      |
| Enhancement         | https://github.com/KinsonDigital/Velaptor/labels/enhancement                         |
| Workflow Changes    | https://github.com/KinsonDigital/Velaptor/labels/workflow                            |
| Code Doc Changes    | https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%93%91documentation%2Fcode    |
| Product Doc Changes | https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%93%9Ddocumentation%2Fproduct |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CalvinWilkinson** [comment]
NO PR REQUIRED

**Comment by kselena** [comment]
Closed Issue without code changes.  (code changes not required)


**Reason:** Forgot to close issues.
