### ISSUE TITLE
🚧Fix broken enhancement label link

### ISSUE THREAD

**Issue by kselena** [KinsonDigital/issues-repo#41]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_\<title\>_**' section.

### Description

The label was changed but the link is still pointing to the old enhancement label.  
The old enhancement label was changed and this is how the link has become broken.

### Acceptance Criteria

**This issue is finished when:**
- [ ] Label link is updated

### ToDo Items

- [ ] Draft pull request created and linked to this issue
- [X] Priority label added to issue.  Refer to _**Change Type Labels**_ section below.
- [X] Issue linked to the proper project
- [X] Issue linked to proper milestone

### Additional information below:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                                                                                |
|---------------------|--------------------------------------------------------------------------------------|
| Bug Fixes           | https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%90%9Bbug                     |
| Breaking Changes    | https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%92%A3breaking%20changes      |
| Enhancement         | https://github.com/KinsonDigital/Velaptor/labels/enhancement                         |
| Workflow Changes    | https://github.com/KinsonDigital/Velaptor/labels/workflow                            |
| Code Doc Changes    | https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%93%91documentation%2Fcode    |
| Product Doc Changes | https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%93%9Ddocumentation%2Fproduct |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CalvinWilkinson** [comment]
Will be implemented in issue below:
- #312
