### ISSUE TITLE
🔬Setup code scanning to research it

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/issues-repo#8]
### ToDo Items

- [ ] Draft pull request created and linked to this issue
- [ ] Priority label added to issue
- [ ] Issue linked to the proper project
- [ ] Issue linked to proper milestone
